### ISSUE TITLE
Droid vpn app in Egypt

### ISSUE THREAD

**Issue by moustafaelkadry** [DroidVPN-Official/DroidVPN#14]
Good morning dear sir or madam , 
 I'm moustafa from Egypt and one of my friend advised me to use your app . But It's very slow and always shutting down and crashing after less than 3 minutes working . 
Can you advise me what's wrong with it? 
I'm using Etisalat and it's only working in Egypt , what is the faster sittings for it ? 
Thanks in advance .

**Comment by ANASABDIALI** [comment]
Great Mr.moustafa am Anas from Somalia 🇸🇴.
I was using Droid vpn for almost a year.
And it good especially for security reasons.
No spyies and hackers can see your device.
And for severs it is according to your country.
Me to I just learnt how to make it on YouTube.
Great day.
