### ISSUE TITLE
Payment Method

### ISSUE THREAD

**Issue by STARSozi** [DroidVPN-Official/DroidVPN#17]
Why Paypal method removed?

I'm strugling with bitcoin

**Comment by STARSozi** [comment]
How can I pay using Bitcoin method, anyone???????

**Comment by sltan1020** [comment]
#

**Comment by sltan1020** [comment]
ssh -T git@hostname
# Attempts to ssh to GitHub Enterprise Server

**Comment by sltan1020** [comment]
#2

**Comment by sltan1020** [comment]
[ssh -T git@hostname # Attempts to ssh to GitHub Enterprise Server](ssh -T git@hostname # Attempts to ssh to GitHub Enterprise Server) 

> #21 #21 #18
