### ISSUE TITLE
The APP say to update to new version and the APP version i Saw here is the same that i have. Please fix it

### ISSUE THREAD

**Issue by Clerico007** [DroidVPN-Official/DroidVPN#2]

**Comment by Amen-Menjli** [comment]
i have the same problem
![image](https://user-images.githubusercontent.com/67660665/94784473-1ecb9b00-03c6-11eb-837e-9367e4205c67.png)

**Comment by STARSozi** [comment]
same problem

**Comment by donaldoalves0** [comment]
same 2

**Comment by 3omer** [comment]
A temporary fix: adjust your PC date to September 2020.

**Comment by STARSozi** [comment]
> A temporary fix: adjust your PC date to September 2020.

thanks dude, it worked, but as u said, a temporary fix

**Comment by donaldoalves0** [comment]
thanks Bro its Working


Omer M. Osman <notifications@github.com> escreveu no dia quinta, 1/10/2020
à(s) 16:22:

**Comment by Takudzwakelvin** [comment]
Thanks bro

**Comment by donaldoalves0** [comment]
Hi, you some trick to to update account with paypal now,

Donaldo Alves Madeira

Técnico de Informática-IT

Youtuber (DuDA DoiT
<https://www.youtube.com/channel/UCpg4AIX-s8QJTdl0oa0TYRQ>)

Cidade de Quelimane

Av. Ahmed Sekou Touré

Mapiazua CP. 2400

<https://www.youtube.com/channel/UCpg4AIX-s8QJTdl0oa0TYRQ>
<https://www.facebook.com/donaldoalvis/> <https://twitter.com/Donaldoalvis>
<https://api.whatsapp.com/send?phone=258848856803>

+258 84 88 56 803

+258 87 88 56 803



Takudzwakelvin <notifications@github.com> escreveu no dia sexta, 2/10/2020
à(s) 06:31:
